#!/usr/bin/env bash

domain="$1"
subdomain="$2"

subdomains=("www" "lb-01" "web-01" "web-02")

if [ -z "$domain" ]; then
  echo "Please provide a domain name as the first argument."
  exit 1
fi

if [ -z "$subdomain" ]; then
  for sub in "${subdomains[@]}"; do
    record_type=$(dig "$sub.$domain" +short -t A | awk '{ print "A" }')
    destination=$(dig "$sub.$domain" +short -t A)
    echo "The subdomain $sub is a $record_type record and points to $destination"
  done
else
  record_type=$(dig "$subdomain.$domain" +short -t A | awk '{ print "A" }')
  destination=$(dig "$subdomain.$domain" +short -t A)
  echo "The subdomain $subdomain is a $record_type record and points to $destination"
fi
