#!/usr/bin/env bash
# Domain zone configuration

domain="$1"
subdomain="$2"

dns_config() {
    local sub
    local result
    local record_type
    
    sub="$1"
    result=$(dig "$sub.$domain" +short)
    record_type=$(dig "$sub.$domain" +short -t A | awk '{print "A"}')
    
    if [ -n "$result" ]; then
        echo "The subdomain $sub is a $record_type record and points to $result"
    else
        echo "The subdomain $sub does not exist or has no DNS records."
    fi
}

if [ "$#" == 1 ]; then
    dns_config "www"
    dns_config "lb-01"
    dns_config "web-01"
    dns_config "web-02"
elif [ "$#" == 2 ]; then
    dns_config "$subdomain"
else
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi
