#!/usr/bin/env bash
# Domain zone configuration

domain="$1"
subdomain="$2"

dns_config() {
    local sub="$1"
    local result
    local record_type

    result=$(dig +short "$sub.$domain")
    record_type=$(dig +short -t A "$sub.$domain" | awk '{print "A"}')

    if [ -n "$result" ]; then
        echo "The subdomain $sub is a $record_type record and points to $result"
    else
        echo "The subdomain $sub does not exist or has no DNS records."
    fi
}

if [ "$#" -eq 1 ]; then
    dns_config "www"
    dns_config "lb-01"
    dns_config "web-01"
    dns_config "web-02"
elif [ "$#" -eq 2 ]; then
    dns_config "$subdomain"
else
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi
