#!/usr/bin/env bash
# Configure a custom 404 page

# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Allow Nginx HTTP traffic
ufw allow 'Nginx HTTP'

# Set permissions for the web root directory
chmod -R 755 /var/www

# Create default "Hello World!" index page
echo 'Hello World!' > /var/www/html/index.html

# Define new configuratyion for Nginx
new_config=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    error_page 404 /404.html;
    location /404.html {
        internal;
    }

    if (\$request_filename ~ redirect_me) {
        rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4
    }
}
"

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Overwrite default Nginx config with the new config
echo "$new_config" > /etc/nginx/sites-available/default

# Check if Nginx is running and start or restart accordingly
if [ "$(pgrep nginx)" -le 0 ];
then
    service nginx start
else
    service nginx restart
fi;
