#!/usr/bin/env bash
# Configure web-02 to be identical to web-01
# The name of the custom HTTP header must be X-served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

# Update the package list
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create necessary directories and set permissions
sudo mkdir -p /var/www/html/ /var/www/error
sudo chmod -R 755 /var/www

# Create a basic HTML file for the default site
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Nginx server block configuration
server_config=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name_;
    add_header X-Served-By \$hostname;
    location / {
        try_files \$uri/ =404;
    }
    if (\$request_filename ~ redirect_me){
        rewrite ^ https://youtube.com permanent;
    }
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}"

# Write the server configuration to Nginx default site
echo "$server_config" | sudo tee /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart
